
@code{Without-interrupts} は、手続き引数が実行されている間、タイムスライシング割り込みを無効にします。}あるいは、マルチプロセッシングコンピュータは、ハードウェアでアトミック操作を直接サポートする命令を提供します。@footnote{test-and-set、test-and-clear、swap、compare-and-exchange、load-reserve、store-conditional など、このような命令には多くの変形があり、その設計はマシンのプロセッサ-メモリインターフェースに慎重に一致させる必要があります。ここで発生する 1 つの問題は、2 つのプロセスがこのような命令を使用してまったく同時に同じリソースを獲得しようとした場合に何が起こるかを判断することです。これには、どのプロセスが制御を取得するかについて決定を下すためのメカニズムが必要です。このようなメカニズムは@newterm{arbiter}と呼ばれます。Arbiter は通常、ある種のハードウェアデバイスに帰着します。残念ながら、arbiter がその決定を下すために任意に長い時間を許可しない限り、100% の時間機能する公正な arbiter を物理的に構築できないことを証明することができます。ここでの基本的な現象は、14 世紀のフランスの哲学者 Jean Buridan がアリストテレスの @i{De caelo} に関する解説で最初に観察しました。Buridan は、2 つの同等に魅力的な食物源の間に置かれた完全に合理的な犬は、どちらに最初に行くかを決定できないため、餓死すると論じました。}

@quotation
@strong{@anchor{Exercise 3.46}練習問題 3.46:} テキストに示されているように、操作をアトミックにすることを試みずに、通常の手続きを使用して @code{test-and-set!} を実装するとします。@ref{図 3.29} のようなタイミング図を描いて、2 つのプロセスが同時に mutex を獲得できるようにすることで mutex 実装がどのように失敗するかを示してください。
@end quotation

@quotation
@strong{@anchor{Exercise 3.47}練習問題 3.47:} セマフォ(サイズ @math{n})は mutex の一般化です。mutex のように、セマフォは獲得と解放操作をサポートしますが、最大 @math{n} 個のプロセスが並行してそれを獲得できるという点でより一般的です。セマフォを獲得しようとする追加のプロセスは、解放操作を待つ必要があります。セマフォの実装を提供してください

@enumerate a

@item
mutex の観点で

@item
アトミック @code{test-and-set!} 操作の観点で。

@end enumerate
@end quotation

@subsubheading デッドロック

シリアライザの実装方法を見てきましたが、上記の @code{serialized-exchange} 手続きを使用しても、口座交換にはまだ問題があることがわかります。Peter が @math{{a1}} を @math{{a2}} と交換しようとし、Paul が同時に @math{{a2}} を @math{{a1}} と交換しようとすると想像してください。Peter のプロセスが @math{{a1}} を保護するシリアル化された手続きに入ったポイントに達し、そのすぐ後に Paul のプロセスが @math{{a2}} を保護するシリアル化された手続きに入ったとします。今、Peter は(@@math{{a2}} を保護するシリアル化された手続きに入るために)Paul が @math{{a2}} を保護するシリアル化された手続きを終了するまで進行できません。同様に、Paul は Peter が @math{{a1}} を保護するシリアル化された手続きを終了するまで進行できません。各プロセスは、もう一方を待って永遠に停止します。この状況は@newterm{デッドロック}と呼ばれます。デッドロックは、複数の共有リソースへの並行アクセスを提供するシステムでは常に危険です。

この状況でデッドロックを回避する 1 つの方法は、各口座に一意の識別番号を付け、プロセスが常に最も番号の小さい口座を保護する手続きに最初に入ろうとするように @code{serialized-exchange} を書き直すことです。この方法は交換問題ではうまく機能しますが、より洗練されたデッドロック回避技術が必要な他の状況や、デッドロックをまったく回避できない場合があります。(@ref{練習問題 3.48} と @ref{練習問題 3.49} を参照してください。)@footnote{共有リソースに番号を付けて順番に獲得することでデッドロックを回避する一般的な技術は、@ref{Havender (1968)} によるものです。デッドロックを回避できない状況では、@newterm{デッドロック回復}方法が必要です。これには、プロセスがデッドロック状態から「バックアウト」して再試行することが含まれます。デッドロック回復メカニズムは、データベース管理システムで広く使用されています。このトピックは @ref{Gray and Reuter 1993} で詳しく扱われています。}

@quotation
@strong{@anchor{Exercise 3.48}練習問題 3.48:} 上記で説明したデッドロック回避方法(つまり、口座に番号が付けられ、各プロセスが最初に番号の小さい口座を獲得しようとする)が交換問題でデッドロックを回避する理由を詳しく説明してください。このアイデアを組み込むために @code{serialized-exchange} を書き直してください。(各口座が番号で作成されるように @code{make-account} を変更する必要もあります。これは適切なメッセージを送信することでアクセスできます。)
@end quotation

@quotation
@strong{@anchor{Exercise 3.49}練習問題 3.49:} 上記で説明したデッドロック回避メカニズムが機能しないシナリオを示してください。(ヒント:交換問題では、各プロセスはアクセスする必要がある口座を事前に知っています。プロセスが必要とする追加の共有リソースを知る前に、いくつかの共有リソースへのアクセスを取得する必要がある状況を考えてください。)
@end quotation

@subsubheading 並行性、時間、通信

異なるプロセスが共有状態にアクセスするときにイベントの順序を制御する必要があることを見てきました。そして、シリアライザの賢明な使用を通じてこの制御を達成する方法を見てきました。しかし、並行性の問題はこれよりも深いところにあります。なぜなら、根本的な観点から、「共有状態」が何を意味するのかが常に明確ではないからです。

@code{test-and-set!} などのメカニズムでは、プロセスが任意の時刻にグローバル共有フラグを調べる必要があります。これは、パイプライン化やキャッシュメモリなどの最適化技術により、メモリの内容が毎瞬間一貫した状態にない可能性がある現代の高速プロセッサで実装するのが問題があり非効率的です。したがって、現代のマルチプロセッシングシステムでは、シリアライザパラダイムは並行性制御への新しいアプローチに取って代わられつつあります。@footnote{シリアル化の代替案の 1 つは@newterm{バリア同期}と呼ばれます。プログラマは、並行プロセスが好きなように実行できるようにしますが、すべてのプロセスがバリアに到達するまでプロセスが通過できない特定の同期点(「バリア」)を確立します。現代のプロセッサは、一貫性が必要な場所で同期点を確立できるようにするマシン命令を提供します。例えば、@abbr{PowerPC} には、この目的のために @abbr{SYNC} と @abbr{EIEIO}(入出力の順序付けられた実行の強制)と呼ばれる 2 つの命令が含まれています。}

共有状態の問題のある側面は、大規模な分散システムでも発生します。例えば、個々の支店銀行が銀行残高のローカル値を維持し、他の支店によって維持される値と定期的に比較する分散銀行システムを想像してください。このようなシステムでは、「口座残高」の値は、同期の直後を除いて、未定義になります。Peter が Paul と共同で保有する口座にお金を預金した場合、口座残高が変更されたと言うべきはいつですか---ローカル支店の残高が変更されたとき、それとも同期後まで待つべきですか?そして、Paul が別の支店から口座にアクセスした場合、動作が「正しい」ように銀行システムに課す合理的な制約は何ですか?正しさにとって重要かもしれない唯一のことは、Peter と Paul が個別に観察した動作と、同期直後の口座の「状態」です。同期間のイベントの「実際の」口座残高または順序に関する質問は、無関係または無意味かもしれません。@footnote{これは奇妙な見方のように思えるかもしれませんが、このように機能するシステムがあります。例えば、クレジットカード口座への国際請求は通常、国ごとに清算され、異なる国で行われた請求は定期的に調整されます。したがって、口座残高は国によって異なる場合があります。}

ここでの基本的な現象は、異なるプロセスを同期したり、共有状態を確立したり、イベントに順序を課したりするには、プロセス間の通信が必要であるということです。本質的に、並行性制御における時間の概念は、通信と密接に結び付いている必要があります。@footnote{分散システムの場合、この観点は @ref{Lamport (1978)} によって追求され、分散システムのイベントの順序を確立するために使用できる「グローバルクロック」を確立するために通信を使用する方法を示しました。}時間と通信の間の同様のつながりが相対性理論にも現れることは興味深いことです。そこでは、光速(イベントを同期するために使用できる最速の信号)が時間と空間を関連付ける基本定数です。計算モデルで時間と状態を扱う際に遭遇する複雑さは、実際には物理宇宙の根本的な複雑さを反映している可能性があります。

@node 3.5, Chapter 4, 3.4, Chapter 3
@section ストリーム

代入をモデリングのツールとして理解し、代入が引き起こす複雑な問題を理解してきました。これらの問題のいくつかを回避するために、別の方法で物事を進めることができたかどうかを尋ねる時が来ました。このセクションでは、@newterm{ストリーム}と呼ばれるデータ構造に基づく状態のモデリングへの代替アプローチを探ります。ストリームは、状態のモデリングの複雑さの一部を緩和できることがわかります。

一歩戻って、この複雑さがどこから来るのかを確認しましょう。現実世界の現象をモデル化する試みで、いくつかの明らかに合理的な決定を下しました:局所状態を持つ現実世界のオブジェクトを、局所変数を持つ計算オブジェクトでモデル化しました。現実世界の時間変化をコンピュータの時間変化と同一視しました。コンピュータ内のモデルオブジェクトの状態の時間変化を、モデルオブジェクトの局所変数への代入で実装しました。

別のアプローチはありますか?コンピュータ内の時間をモデル化された世界の時間と同一視することを避けることができますか?変化する世界の現象をモデル化するために、モデルを時間とともに変化させる必要がありますか?数学関数の観点から問題を考えてください。量 @math{x} の時間変化する動作を時間 @math{{x(t)}} の関数として記述できます。@math{x} を瞬間ごとに集中すると、それを変化する量と考えます。しかし、値の全体の時間履歴に集中すると、変化を強調しません---関数自体は変化しません。@footnote{物理学者は、粒子の「世界線」を運動について推論するためのデバイスとして導入することで、この見方を採用することがあります。また、これが信号処理システムについて考える自然な方法であることも既に述べました(@ref{2.2.3})。@ref{3.5.3} でストリームの信号処理への応用を探ります。}

時間が離散的なステップで測定される場合、時間関数を(おそらく無限の)シーケンスとしてモデル化できます。このセクションでは、モデル化されているシステムの時間履歴を表すシーケンスの観点で変化をモデル化する方法を見ていきます。これを達成するために、@newterm{ストリーム}と呼ばれる新しいデータ構造を導入します。抽象的な観点から、ストリームは単なるシーケンスです。しかし、(@ref{2.2.1} のように)ストリームをリストとして単純に実装しても、ストリーム処理の力を完全には明らかにしないことがわかります。代替として、@newterm{遅延評価}の技術を導入します。これにより、非常に大きな(さらには無限の)シーケンスをストリームとして表現できます。

ストリーム処理により、代入や可変データを使用せずに状態を持つシステムをモデル化できます。これには、理論的および実用的の両方で重要な意味があります。なぜなら、代入の導入に固有の欠点を回避するモデルを構築できるからです。一方、ストリームフレームワークは独自の困難を引き起こし、どのモデリング技術がより
