仕事が広く採用され、他のテキストに組み込まれていることを嬉しく思います。私たちの学生がこの本のアイデアとプログラムを取り入れ、新しいコンピュータシステムと言語のコアとして構築するのを見てきました。古代のタルムードの駄洒落の文字通りの実現において、私たちの学生は私たちの建設者になりました。私たちはそのような有能な学生とそのような熟練した建設者を持っていることに幸運です。

この版の準備において、私たちは、@abbr{MIT}や他の場所での私たち自身の教育経験と同僚のコメントによって提案された何百もの明確化を組み込みました。私たちは、汎用算術システム、インタプリタ、レジスタマシンシミュレータ、コンパイラなど、本の主要なプログラミングシステムのほとんどを再設計しました。また、@abbr{IEEE} Scheme標準（@ref{IEEE 1990}）に準拠するScheme実装がコードを実行できるように、すべてのプログラム例を書き直しました。

この版は、いくつかの新しいテーマを強調しています。これらの中で最も重要なのは、計算モデルにおける時間を扱うさまざまなアプローチによって果たされる中心的な役割です：状態を持つオブジェクト、並行プログラミング、関数型プログラミング、遅延評価、非決定性プログラミング。私たちは、並行性と非決定性に関する新しいセクションを含め、このテーマを本全体に統合しようとしました。

本の第1版は、私たちの@abbr{MIT}の1学期科目のシラバスに密接に従っていました。第2版のすべての新しい素材では、1学期ですべてをカバーすることはできないため、インストラクターは選択する必要があります。私たち自身の教育では、論理プログラミングのセクション（@ref{4.4}）をスキップすることがあり、学生にレジスタマシンシミュレータを使用させますが、その実装はカバーしません（@ref{5.2}）。また、コンパイラの簡単な概要のみを提供します（@ref{5.5}）。それでも、これは依然として集中的なコースです。一部のインストラクターは、最初の3つまたは4つの章のみをカバーし、他の素材を後続のコースに残すことを望むかもしれません。

World-Wide-Webサイト@url{http://mitpress.mit.edu/sicp}は、この本のユーザーのサポートを提供します。これには、本のプログラム、サンプルプログラミング課題、補足素材、およびLispのScheme方言のダウンロード可能な実装が含まれます。

@node    Preface 1e, Acknowledgments, Preface, Top
@unnumbered 初版への序文

@quotation
コンピュータはバイオリンのようなものです。初心者が最初に蓄音機を試し、次にバイオリンを試すことを想像できます。後者は、彼は言います、ひどい音がします。それは私たちが人文主義者とほとんどのコンピュータ科学者から聞いた議論です。コンピュータプログラムは、彼らは言います、特定の目的には適していますが、柔軟ではありません。バイオリンもタイプライターも、使い方を学ぶまでは柔軟ではありません。

---Marvin Minsky、@cite{Why Programming Is a Good Medium for Expressing
Poorly-Understood and Sloppily-Formulated Ideas}
@end quotation


@noindent
「コンピュータプログラムの構造と解釈」は、マサチューセッツ工科大学のコンピュータサイエンスの入門レベルの科目です。電気工学またはコンピュータサイエンスを専攻する@abbr{MIT}のすべての学生に必要とされ、「共通コアカリキュラム」の4分の1として、回路と線形システムに関する2つの科目とデジタルシステムの設計に関する科目も含まれています。私たちは1978年以来この科目の開発に関与しており、1980年の秋以来、この素材を現在の形式で毎年600から700人の学生に教えてきました。これらの学生のほとんどは、計算に関する正式な訓練をほとんどまたはまったく受けていませんが、多くの学生がコンピュータで少し遊んでおり、数人は広範なプログラミングまたはハードウェア設計の経験を持っています。

この入門コンピュータサイエンス科目の私たちの設計は、2つの主要な懸念を反映しています。第一に、私たちは、コンピュータ言語は単にコンピュータに操作を実行させる方法ではなく、むしろ方法論に関するアイデアを表現するための新しい形式的媒体であるという考えを確立したいと考えています。したがって、プログラムは人々が読むために書かれなければならず、機械が実行するのは偶然です。第二に、このレベルの科目によって扱われるべき本質的な素材は、特定のプログラミング言語構造の構文でも、特定の関数を効率的に計算するための巧妙なアルゴリズムでも、アルゴリズムの数学的分析と計算の基礎でもなく、むしろ大規模なソフトウェアシステムの知的複雑性を制御するために使用される技術であると信じています。

私たちの目標は、この科目を完了した学生が、プログラミングのスタイルと美学の要素をよく理解することです。彼らは、大規模なシステムで複雑性を制御するための主要な技術を習得すべきです。彼らは、模範的なスタイルで書かれている場合、50ページの長さのプログラムを読むことができるべきです。彼らは、何を読まないか、そして何をいつでも理解する必要がないかを知っているべきです。彼らは、元の著者の精神とスタイルを保持しながら、プログラムを変更することについて安心感を持つべきです。

これらのスキルは、コンピュータプログラミングに固有のものではありません。私たちが教え、頼りにする技術は、すべてのエンジニアリング設計に共通しています。私たちは、適切な場合に詳細を隠す抽象化を構築することによって複雑性を制御します。私たちは、標準的でよく理解された部品を「ミックスアンドマッチ」方式で組み合わせてシステムを構築できるようにする従来のインタフェースを確立することによって複雑性を制御します。私たちは、設計の特定の側面を強調し、他の側面を強調しない、設計を記述するための新しい言語を確立することによって複雑性を制御します。

この科目への私たちのアプローチの根底にあるのは、「コンピュータサイエンス」は科学ではなく、その意義はコンピュータとはほとんど関係がないという私たちの信念です。コンピュータ革命は、私たちの考え方と、私たちが考えることを表現する方法における革命です。この
