この本は、コンピュータの中に生きる精神に、敬意と賞賛を込めて捧げられています。

@quotation
「コンピュータサイエンスにおいて、コンピューティングの楽しさを保つことは非常に重要だと思います。始まった当初、それはとても楽しいものでした。もちろん、支払いをする顧客は時々ひどい目に遭い、しばらくすると私たちは彼らの苦情を真剣に受け止め始めました。私たちは、これらの機械の成功した、エラーのない完璧な使用に本当に責任があるかのように感じ始めました。そうではないと思います。私たちは、それらを拡張し、新しい方向に進め、楽しさを家に保つ責任があると思います。コンピュータサイエンスの分野が楽しさの感覚を決して失わないことを願っています。何よりも、私たちが宣教師にならないことを願っています。聖書のセールスマンのように感じないでください。世界にはすでにそのような人が多すぎます。コンピューティングについてあなたが知っていることを、他の人々も学ぶでしょう。成功したコンピューティングへの鍵があなたの手の中だけにあるとは感じないでください。あなたの手の中にあるのは、知性だと私は思い、願っています：最初に導かれたときよりも機械を多くのものとして見る能力、それをより多くのものにすることができる能力です。」

@noindent
---Alan J. Perlis（1922年4月1日 - 1990年2月7日）
@end quotation

@node    Foreword, Preface, Dedication, Top
@unnumbered 序文

教育者、将軍、栄養士、心理学者、そして親はプログラムします。軍隊、学生、そしていくつかの社会はプログラムされます。大きな問題への攻撃は、一連のプログラムを使用し、そのほとんどは途中で存在するようになります。これらのプログラムは、手元の問題に特有であると思われる問題で満ちています。プログラミングをそれ自体の知的活動として理解するには、コンピュータプログラミングに目を向ける必要があります。コンピュータプログラムを読み書きする必要があります---それらの多くを。プログラムが何についてであるか、またはどのようなアプリケーションに役立つかはあまり重要ではありません。重要なのは、それらがどれだけうまく実行され、さらに大きなプログラムの作成において他のプログラムとどれだけスムーズに適合するかです。プログラマーは、部分の完璧さと集合の適切さの両方を求めなければなりません。この本では、「プログラム」の使用は、デジタルコンピュータ上で実行するためのLispの方言で書かれたプログラムの作成、実行、および研究に焦点を当てています。Lispを使用することで、私たちはプログラムできるものを制限または限定するのではなく、プログラムの記述の表記法のみを制限します。

この本の主題に関する私たちのやり取りは、3つの現象の焦点に関係しています：人間の心、コンピュータプログラムの集合、そしてコンピュータ。すべてのコンピュータプログラムは、心の中で孵化した、現実または精神的プロセスのモデルです。これらのプロセスは、人間の経験と思考から生じ、数が膨大で、詳細が複雑で、いつでも部分的にしか理解されていません。これらは、私たちのコンピュータプログラムによって永続的な満足度までモデル化されることはめったにありません。したがって、私たちのプログラムは慎重に手作りされた離散的なシンボルの集合、連動する機能のモザイクですが、それらは絶えず進化します：モデルの認識が深まり、拡大し、一般化するにつれて、プログラムを変更します。最終的にモデルは、私たちが苦労している別のモデル内で準安定した場所を獲得します。コンピュータプログラミングに関連する高揚の源は、プログラムとして表現されたメカニズムの心とコンピュータ内での継続的な展開と、それらが生成する認識の爆発です。芸術が私たちの夢を解釈するならば、コンピュータはプログラムの装いでそれらを実行します！

そのすべての力にもかかわらず、コンピュータは厳しい監督者です。そのプログラムは正しくなければならず、私たちが言いたいことはすべての詳細で正確に言われなければなりません。他のすべての象徴的活動と同様に、私たちは議論を通じてプログラムの真実を確信するようになります。Lisp自体には意味論（ところで、別のモデル）を割り当てることができ、プログラムの関数が述語計算で指定できる場合、論理の証明方法を使用して受け入れられる正しさの議論を行うことができます。残念ながら、プログラムが大きく複雑になるにつれて、ほとんど常にそうであるように、仕様自体の適切性、一貫性、正しさが疑わしくなるため、完全な形式的な正しさの議論が大きなプログラムに伴うことはめったにありません。大きなプログラムは小さなプログラムから成長するため、その正しさを確信するようになった標準的なプログラム構造の武器を開発することが重要です---私たちはそれらをイディオムと呼びます---そして、実証された価値のある組織技術を使用してそれらをより大きな構造に組み合わせる方法を学びます。これらの技術はこの本で詳しく扱われており、それらを理解することは、プログラミングと呼ばれるプロメテウス的事業への参加に不可欠です。何よりも、強力な組織技術の発見と習得は、大規模で重要なプログラムを作成する能力を加速します。逆に、大きなプログラムを書くことは非常に骨の折れる作業であるため、大きなプログラムに適合させる必要がある機能と詳細の量を削減する新しい方法を発明するように刺激されます。

プログラムとは異なり、コンピュータは物理法則に従わなければなりません。高速に実行したい場合---状態変化ごとに数ナノ秒---電子をわずかな距離（最大で@math{{1 {1\over2}}}フィート）しか送信してはなりません。空間に集中した膨大な数のデバイスによって生成される熱は除去する必要があります。機能の多様性とデバイスの密度のバランスをとる繊細なエンジニアリング技術が開発されました。いずれにせよ、ハードウェアは常に、私たちがプログラムを気にするレベルよりも原始的なレベルで動作します。Lispプログラムをマシンプログラムに変換するプロセスは、それ自体が私たちがプログラムする抽象的なモデルです。それらの研究と作成は、任意のモデルのプログラミングに関連する組織プログラムへの多くの洞察を与えます。もちろん、コンピュータ自体もそのようにモデル化できます。考えてみてください：最小の物理的スイッチング要素の動作は、微分方程式で記述される量子力学によってモデル化され、その詳細な動作は、@dots{}で構成されるコンピュータ上で実行されるコンピュータプログラムで表される数値近似によってキャプチャされます！

3つの焦点を個別に識別することは、単なる戦術的便宜の問題ではありません。彼らが言うように、それはすべて頭の中にありますが、この論理的な分離は、これらの焦点間の象徴的トラフィックの加速を誘発し、その豊かさ、活力、および可能性は、人間の経験において生命そのものの進化によってのみ超えられます。せいぜい、焦点間の関係は準安定です。コンピュータは決して十分に大きくも速くもありません。各
