これを使用して、@code{fixed-point}、@code{average-damp}、および@ref{Exercise 1.43}の@code{repeated}手続きを用いて@math{n^{\text{th}}}乗根を計算する簡単な手続きを実装してください。必要な算術演算はすべてプリミティブとして利用可能であると仮定してください。
@end quotation

@quotation
@strong{@anchor{Exercise 1.46}練習問題 1.46:} この章で説明したいくつかの数値計算法は、@newterm{反復改善}として知られる非常に一般的な計算戦略のインスタンスです。反復改善は、何かを計算するために、答えの初期推測から始め、推測が十分良いかどうかをテストし、そうでなければ推測を改善してその改善された推測を新しい推測として使用してプロセスを続けるというものです。2つの手続きを引数として受け取る手続き@code{iterative-improve}を書いてください：推測が十分良いかどうかを判定する方法と、推測を改善する方法です。@code{Iterative-improve}は、推測を引数として受け取り、推測が十分良くなるまで改善し続ける手続きを値として返すべきです。@ref{1.1.7}の@code{sqrt}手続きと@ref{1.3.3}の@code{fixed-point}手続きを@code{iterative-improve}を用いて書き直してください。
@end quotation

@node    Chapter 2, 2.1, 1.3, Top
@chapter データによる抽象化の構築

@quotation
我々は今、数学的抽象化の決定的なステップに至ります：記号が何を表すかを忘れるのです。@dots{} [数学者は] 怠惰である必要はありません。これらの記号が表すものを見ることなく、これらの記号で実行できる多くの演算があります。

---ヘルマン・ワイル、@cite{数学的思考法}
@end quotation


@noindent
@ref{Chapter 1}では、計算プロセスとプログラム設計における手続きの役割に焦点を当てました。プリミティブデータ（数）とプリミティブ演算（算術演算）の使用方法、合成、条件分岐、およびパラメータの使用を通じて手続きを組み合わせて複合手続きを形成する方法、そして@code{define}を使用して手続きを抽象化する方法を見ました。手続きをプロセスの局所的進化のパターンと見なすことができること、そして手続きに具体化された一般的なプロセスのパターンについて分類し、推論し、単純なアルゴリズム解析を行いました。また、高階手続きが、計算の一般的な手法を操作し、それによってその観点から推論することを可能にすることで、言語の力を高めることも見ました。これがプログラミングの本質の大部分です。

この章では、より複雑なデータを見ていきます。第1章のすべての手続きは単純な数値データを操作しますが、単純なデータだけでは、計算を使用して対処したい多くの問題には十分ではありません。プログラムは通常、複雑な現象をモデル化するように設計されており、多くの側面を持つ現実世界の現象をモデル化するには、いくつかの部分を持つ計算オブジェクトを構築する必要があります。したがって、第1章での焦点が手続きを組み合わせて複合手続きを形成することで抽象化を構築することであったのに対し、この章では、あらゆるプログラミング言語のもう1つの重要な側面である、データオブジェクトを組み合わせて@newterm{複合データ}を形成するために提供される手段に目を向けます。

プログラミング言語に複合データが必要なのはなぜでしょうか？複合手続きが必要な理由と同じです：プログラムを設計できる概念レベルを引き上げ、設計のモジュール性を高め、言語の表現力を強化するためです。手続きを定義する能力が言語のプリミティブ演算よりも高い概念レベルでプロセスを扱えるようにするのと同様に、複合データオブジェクトを構築する能力は、言語のプリミティブデータオブジェクトよりも高い概念レベルでデータを扱えるようにします。

有理数の算術演算を行うシステムを設計するタスクを考えてみましょう。2つの有理数を受け取り、その和を生成する演算@code{add-rat}を想像できます。単純なデータの観点から言えば、有理数は2つの整数、つまり分子と分母として考えることができます。したがって、各有理数が2つの整数（分子と分母）で表され、@code{add-rat}が2つの手続き（和の分子を生成するものと分母を生成するもの）によって実装されるプログラムを設計できます。しかし、これは不便です。なぜなら、どの分子がどの分母に対応するかを明示的に追跡する必要があるからです。多くの有理数に対して多くの演算を実行することを意図したシステムでは、このような簿記の詳細がプログラムをかなり雑然とさせてしまい、我々の心にどんな影響を及ぼすかは言うまでもありません。分子と分母を「接着」してペア---@newterm{複合データオブジェクト}---を形成し、プログラムが有理数を単一の概念単位として扱うのと一貫した方法で操作できる方がはるかに良いでしょう。

複合データの使用はまた、プログラムのモジュール性を高めることも可能にします。有理数をそれ自体でオブジェクトとして直接操作できる場合、有理数自体を扱うプログラムの部分と、有理数が整数のペアとしてどのように表現されるかの詳細を分離できます。データオブジェクトがどのように表現されているかを扱うプログラムの部分と、データオブジェクトがどのように使用されるかを扱うプログラムの部分を分離する一般的な技法は、@newterm{データ抽象化}と呼ばれる強力な設計方法論です。データ抽象化がプログラムの設計、保守、変更をはるかに容易にする方法を見ていきます。

複合データの使用は、プログラミング言語の表現力の真の向上につながります。「線形結合」@math{{ax + by}}を形成するという考え方を考えてみましょう。@math{a}、@math{b}、@math{x}、@math{y}を引数として受け取り、@math{{ax + by}}の値を返す手続きを書きたいかもしれません。これは
