
レジスタと操作

* 5.4.1::            明示的制御評価器の中核
* 5.4.2::            逐次評価と末尾再帰
* 5.4.3::            条件式、代入、定義
* 5.4.4::            評価器の実行

コンパイラの概要

* 5.5.1::            コンパイラの構造
* 5.5.2::            式のコンパイル
* 5.5.3::            組み合わせのコンパイル
* 5.5.4::            命令列の結合
* 5.5.5::            コンパイル済みコードの例
* 5.5.6::            字句アドレス指定
* 5.5.7::            コンパイル済みコードと評価器のインタフェース

@end detailmenu
@end menu

@node    UTF, Dedication, Top, Top
@unnumbered 非公式Texinfo形式

これは第2版の@abbr{SICP}書籍です。@*非公式Texinfo形式から作成されています。

おそらくあなたは、EmacsのInfoモードのようなInfoハイパーテキストブラウザでこれを読んでいるでしょう。あるいは、画面やプリンタで@TeX{}形式で読んでいるかもしれませんが、それは賢明ではないでしょう。そして、印刷すると高価です。

自由に配布されている公式の@abbr{HTML}および@abbr{GIF}形式は、2001年4月の長いEmacs愛好家の週末に、Lytha Aythによって個人的に非公式Texinfo形式（@abbr{UTF}）バージョン1に最初に変換されました。

@abbr{UTF}は@abbr{HTML}形式よりも検索が容易です。また、386ベースの寄贈されたPCのような控えめなコンピュータを使用している人々にとって、はるかにアクセスしやすいです。理論的には、386はLinux、Emacs、Schemeインタプリタを同時に実行できますが、ほとんどの386は、Netscapeと必要なX Window Systemの両方を、若い資金不足のハッカーに@newterm{スラッシング}の概念を早期に紹介することなく実行することはおそらくできません。@abbr{UTF}は、圧縮せずに1.44@abbr{MB}のフロッピーディスケットに収まることもでき、インターネットや@abbr{LAN}アクセスがないPCに@abbr{UTF}をインストールする際に便利です。

Texinfo変換は、可能な限り直接的な翻字でした。@TeX{}から@abbr{HTML}への変換と同様に、これは多少の破損を伴いました。非公式Texinfo形式の場合、図は@abbr{ASCII}の失われた技術の素人的な復活に苦しんでいます。また、多数の上付き文字（'^'）と下付き文字（'_'）の変換中に、いくつかの曖昧さのエラーが導入された可能性があります。@emph{どれ}であるかを推測することは、読者への演習として残されています。しかし、少なくとも私たちは、@emph{以上または等しい}記号を@code{<u>&gt;</u>}としてエンコードすることで、勇敢な宇宙飛行士をリスクにさらすことはしません。

エラーを修正したり@abbr{ASCII}アートを改善したりするために@file{sicp.texi}を変更する場合は、@code{@@set utfversion @value{utfversion}}行を更新してデルタを反映してください。たとえば、Lythaのバージョン@code{1}から始めた場合で、あなたの名前がBobの場合、連続するバージョンに@code{1.bob1}、@code{1.bob2}、@dots{} @code{1.bob@i{n}}のような名前を付けることができます。また、@code{utfversiondate}も更新してください。Web上でバージョンを配布したい場合は、ファイルまたはWebページのどこかに文字列「sicp.texi」を埋め込むと、Webサーチエンジンで見つけやすくなります。

非公式Texinfo形式は、寛大に自由に配布された@abbr{HTML}バージョンの精神に沿っていると考えられています。しかし、誰かの弁護士の艦隊が何かすることを必要とし、何か良性の些細なことで困惑するかもしれないことは決してわかりません。そのため、フルネームを使用したり、アカウントやマシン名を埋め込む可能性のあるInfo、@abbr{DVI}、PostScript、または@abbr{PDF}形式を配布する前に、よく考えてください。
@i{平和を、Lytha Ayth}

@b{補遺:} AbelsonとSussmanによる@abbr{SICP}ビデオ講義も参照してください：
@url{http://groups.csail.mit.edu/mac/classes/6.001/abelson-sussman-lectures/, @abbr{MIT CSAIL}}または
@url{http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video-lectures/, @abbr{MIT OCW}}。

@b{第2の補遺:} 上記は2001年の@abbr{UTF}のオリジナルの序文です。10年後、@abbr{UTF}は変革されました：数学記号と数式は適切に組版され、図はベクトルグラフィックスで描画されています。元のテキスト式と@abbr{ASCII}アート図は、Texinfoソースにまだ存在していますが、Info出力にコンパイルされた場合にのみ表示されます。電子書籍リーダーとタブレットの黎明期において、画面で@abbr{PDF}を読むことは公式にはもはや愚かではありません。楽しんでください！
@i{A.R、2011年5月}

@b{第3の補遺:} 物事は螺旋状に進みます。私たちは、@abbr{PDF}書籍の組版におけるTexinfoとLaTeXの力を探求しました。
今度は@abbr{HTML}に戻る時です。今回は@abbr{HTML5}になります。「それは危険な場所かもしれませんが、平和のための私たちの最後で最良の希望です。」（Sinclair、@cite{@w{Babylon 5}}。）ブラウザ戦争の後に平和は続いているでしょうか？とにかく、プロジェクトの目的は、@abbr{HTML5}ツールボックスを使用してLaTeX出力の品質に近づくことです。JavaScript、@abbr{CSS3}、@abbr{SVG}、MathJax、MathML、およびWebフォントがここで採用されています。この事業の実験的な性質により、一部のブラウザではエラーや不具合があります。技術的および芸術的な支援は歓迎されます。その間、本を楽しんで、@abbr{REPL}を起動してください！
@i{A.R、2014年1月}

@node    Dedication, Foreword, UTF, Top
@unnumbered 献辞

