                   (stream-cdr stream)))))
@end lisp
@end quotation

@quotation
@strong{@anchor{Exercise 4.74}Exercise 4.74:} Alyssa P. Hackerは、@code{negate}、
@code{lisp-value}、@code{find-assertions}で、より単純なバージョンの
@code{stream-flatmap}を使うことを提案しています。彼女は、これらのケースで
フレームストリーム上でマップされる手続きは常に空のストリームまたは単一要素
ストリームのいずれかを生成するため、これらのストリームを結合するときに
インターリーブは必要ないと指摘しています。

@enumerate a

@item
Alyssaのプログラムの欠けている式を埋めてください。

@lisp
(define (simple-stream-flatmap proc s)
  (simple-flatten (stream-map proc s)))

(define (simple-flatten stream)
  (stream-map ⟨??⟩
              (stream-filter ⟨??⟩
                             stream)))
@end lisp

@item
この方法で変更すると、クエリシステムの動作は変わりますか？

@end enumerate
@end quotation

@quotation
@strong{@anchor{Exercise 4.75}Exercise 4.75:} クエリ言語のために、@code{unique}と
呼ばれる新しい特殊形式を実装してください。@code{Unique}は、指定されたクエリを
満たすデータベース内の項目が正確に1つある場合に成功するはずです。たとえば、

@lisp
(unique (job ?x (computer wizard)))
@end lisp

@noindent
は、Benが唯一のコンピュータウィザードなので、1項目のストリーム

@lisp
(unique (job (Bitdiddle Ben)
             (computer wizard)))
@end lisp

@noindent
を印刷するはずです。そして

@lisp
(unique (job ?x (computer programmer)))
@end lisp

@noindent
は、複数のコンピュータプログラマーがいるため、空のストリームを印刷するはずです。
さらに、

@lisp
(and (job ?x ?j)
     (unique (job ?anyone ?j)))
@end lisp

@noindent
は、1人だけが担当するすべての仕事と、それを担当する人をリストするはずです。

@code{unique}を実装するには2つの部分があります。最初は、この特殊形式を処理する
手続きを書くことで、2番目は@code{qeval}がその手続きにディスパッチするようにする
ことです。2番目の部分は些細なことです。なぜなら、@code{qeval}はディスパッチを
データ指向の方法で行うからです。手続きが@code{uniquely-asserted}と呼ばれる場合、
必要なのは

@lisp
(put 'unique 'qeval uniquely-asserted)
@end lisp

@noindent
だけで、@code{qeval}は@code{type}（@code{car}）がシンボル@code{unique}である
すべてのクエリに対してこの手続きにディスパッチします。

本当の問題は、手続き@code{uniquely-asserted}を書くことです。これは、@code{unique}
クエリの@code{contents}（@code{cdr}）とフレームのストリームを入力として取る
必要があります。ストリーム内の各フレームに対して、@code{qeval}を使って、与えられた
クエリを満たすフレームへのすべての拡張のストリームを見つける必要があります。
正確に1つの項目を持たないストリームは排除する必要があります。残りのストリームは、
@code{unique}クエリの結果である1つの大きなストリームに累積されるために返されます。
これは@code{not}特殊形式の実装に似ています。

正確に1人を監督するすべての人をリストするクエリを形成して、実装をテストして
ください。
@end quotation

@quotation
@strong{@anchor{Exercise 4.76}Exercise 4.76:} クエリの直列結合としての@code{and}の
実装（@ref{Figure 4.5}）はエレガントですが、@code{and}の2番目のクエリを処理する際に、
最初のクエリによって生成された各フレームに対してデータベースをスキャンしなければ
ならないため、非効率的です。データベースに@math{n}個の要素があり、典型的なクエリが
@math{n}に比例する数の出力フレーム（たとえば@math{{n \,/\, k}}）を生成する場合、
最初のクエリによって生成された各フレームに対してデータベースをスキャンするには、
パターンマッチャーへの@math{{n^2 /\, k}}回の呼び出しが必要になります。別の
アプローチは、@code{and}の2つの節を個別に処理し、次に互換性のある出力フレームの
すべてのペアを探すことです。各クエリが@math{{n \,/\, k}}個の出力フレームを生成する
場合、これは@math{{n^2 /\, k^2}}回の互換性チェックを実行する必要があることを
意味します---現在の方法で必要なマッチ数より@math{k}倍少なくなります。

この戦略を使う@code{and}の実装を考案してください。2つのフレームを入力として取り、
フレーム内の束縛が互換性があるかどうかをチェックし、そうであれば、2つの束縛の
集合をマージするフレームを生成する手続きを実装する必要があります。この操作は
単一化に似ています。
@end quotation

@quotation
@strong{@anchor{Exercise 4.77}Exercise 4.77:} @ref{4.4.3}で、@code{not}と
@code{lisp-value}が、これらのフィルタリング操作が変数が未束縛のフレームに
適用される場合に、クエリ言語が「間違った」答えを与える原因になる可能性があることを
見ました。この欠点を修正する方法を考案してください。1つのアイデアは、フィルタリングを
「遅延」方式で実行し、操作を可能にするのに十分な変数が束縛されたときにのみ満たされる
フィルタリングの「約束」をフレームに追加することです。すべての他の操作が実行
されるまでフィルタリングの実行を待つことができます。しかし、効率のために、
生成される中間フレームの数を減らすために、できるだけ早くフィルタリングを実行
したいと考えます。
@end quotation

@quotation
@strong{@anchor{Exercise 4.78}Exercise 4.78:} クエリ言語を、ストリームプロセスとして
ではなく、@ref{4.3}の評価器を使って実装される非決定性プログラムとして再設計して
ください。このアプローチでは、各クエリは（すべての答えのストリームではなく）
単一の答えを生成し、ユーザーは@code{try-again}を入力してより多くの答えを見る
ことができます。このセクションで構築したメカニズムの多くが非決定性検索と
バックトラッキングによって包含されることがわかるでしょう。しかし、新しいクエリ
言語がここで実装されたものと微妙に異なる動作をすることもわかるでしょう。この
違いを示す例を見つけることができますか？
@end quotation

@quotation
@strong{@anchor{Exercise 4.79}Exercise 4.79:} @ref{4.1}でLisp評価器を実装したとき、
手続きのパラメータ間の名前の競合を避けるためにローカル環境を使う方法を見ました。
たとえば、次を評価するとき

@lisp
(define (square x)
  (* x x))

(define (sum-of-squares x y)
  (+ (square x) (square y)))

(sum-of-squares 3 4)
@end lisp

@noindent
@code{square}の@code{x}と@code{sum-of-squares}の@code{x}の間に混乱はありません。
なぜなら、各手続きの本体を、ローカル変数の束縛を含むように特別に構築された
環境で評価するからです。クエリシステムでは、規則を適用する際の名前の競合を避ける
ために異なる戦略を使いました。規則を適用するたびに、一意であることが保証された
新しい名前で変数を改名します。Lisp評価器の類似の戦略は、ローカル環境を廃止し、
手続きを適用するたびに手続きの本体内の変数を単に改名することです。

クエリ言語のために、改名ではなく環境を使う規則適用方法を実装してください。
環境構造を基にして、ブロック構造手続きの規則版のような大規模システムを扱うための
クエリ言語の構造を作成できるかどうかを確認してください。これのいずれかを、
コンテキストでの推論の問題に関連付けることができますか（たとえば、「@math{P}が
真だと仮定すると、@math{A}と@math{B}を推論できるだろう。」）問題解決の方法として？
（この問題はオープンエンドです。良い答えはおそらくPh.D.の価値があります。）
@end quotation

@node    Chapter 5, 5.1, 4.4, Top
@chapter レジスタマシンを用いた計算

@quotation
私の目的は、天体の機械が神聖で生きた存在の一種ではなく、時計仕掛けの一種である
ことを示すことです（そして、時計が魂を持つと信じる人は、製作者の栄光を作品に
帰すものです）。ほとんどすべての多様な運動が最も単純で物質的な力によって引き起こ
されるのと同じように、時計のすべての運動が単一の重りによって引き起こされるのです。

---Johannes Kepler（Herwart von Hohenburgへの手紙、1605年）
@end quotation


@noindent
私たちは、プロセスを研究し、Lispで書かれた手続きの観点からプロセスを記述する
ことで、この本を始めました。これらの手続きの意味を説明するために、一連の評価
モデルを使いました：@ref{Chapter 1}の置換モデル、@ref{Chapter 3}の環境モデル、
@ref{Chapter 4}のメタ循環評価器。特にメタ循環評価器の検討により、Lisp風言語が
どのように解釈されるかの多くの謎が解消されました。しかし、メタ循環評価器でさえ、
Lispシステムの制御メカニズムを解明できないため、重要な疑問に答えられません。
たとえば、評価器は、部分式の評価がこの値を使う式に値を返す方法を説明しません。
また、評価器は、一部の再帰手続きが反復プロセスを生成する（つまり、一定の空間を
使って評価される）のに対し、他の再帰手続きが再帰プロセスを生成する理由を説明
しません。これらの質問は、メタ循環評価器自体がLispプログラムであり、したがって
基盤となるLispシステムの制御構造を継承するため、未解決のままです。Lisp評価器の
制御構造のより完全な記述を提供するには、Lisp自体よりも原始的なレベルで作業
しなければなりません。

この章では、従来のコンピュータの段階的な操作の観点からプロセスを説明します。
このようなコンピュータ、または@newterm{レジスタマシン}は、@newterm{レジスタ}と
呼ばれる固定された記憶要素のセットの内容を操作する@newterm{命令}を順次実行します。
典型的なレジスタマシン命令は、いくつかのレジスタの内容に原始操作を適用し、
結果を別のレジスタに割り当てます。レジスタマシンによって実行されるプロセスの
記述は、従来のコンピュータの「機械語」プログラムによく似ています。しかし、
特定のコンピュータの機械語に焦点を当てるのではなく、いくつかのLisp手続きを
検討し、各手続きを実行するための特定のレジスタマシンを設計します。したがって、
機械語コンピュータプログラマーではなく、ハードウェアアーキテクトの観点から
タスクにアプローチします。レジスタマシンを設計する際に、再帰などの重要な
プログラミング構造を実装するためのメカニズムを開発します。また、レジスタマシンの
設計を記述するための言語も提示します。@ref{5.2}では、これらの記述を使って
設計したマシンをシミュレートするLispプログラムを実装します。

レジスタマシンのほとんどの原始操作は非常に単純です。たとえば、操作は2つの
レジスタから取得した数値を加算し、3番目のレジスタに格納される結果を生成する
かもしれません。このような操作は、簡単に説明できるハードウェアによって実行
できます。しかし、リスト構造を扱うためには、精巧な記憶割り当てメカニズムを
必要とするメモリ操作@code{car}、@code{cdr}、@code{cons}も使います。@ref{5.3}で、
より基本的な操作の観点からそれらの実装を研究します。

@ref{5.4}では、単純な手続きをレジスタマシンとして定式化する経験を積んだ後、
@ref{4.1}のメタ循環評価器によって記述されたアルゴリズムを実行するマシンを
設計します。これにより、評価器の制御メカニズムの明示的なモデルを提供することで、
Scheme式がどのように解釈されるかの理解のギャップを埋めます。@ref{5.5}では、
Schemeプログラムを、評価器レジスタマシンのレジスタと操作で直接実行できる命令の
シーケンスに変換する単純なコンパイラを研究します。

@menu
* 5.1::              レジスタマシンの設計
* 5.2::              レジスタマシンシミュレータ
* 5.3::              記憶割り当てとガベージコレクション
* 5.4::              明示的制御評価器
* 5.5::              コンパイル
@end menu

@node	5.1, 5.2, Chapter 5, Chapter 5
@section レジスタマシンの設計

レジスタマシンを設計するには、その@newterm{データパス}（レジスタと操作）と、
これらの操作を順序付ける@newterm{コントローラ}を設計する必要があります。単純な
レジスタマシンの設計を説明するために、2つの整数の最大公約数（@abbr{GCD}）を
計算するために使われるユークリッドアルゴリズムを検討しましょう。@ref{1.2.5}で
見たように、ユークリッドアルゴリズムは、次の手続きで指定される反復プロセスに
よって実行できます：

@lisp
(define (gcd a b)
  (if (= b 0)
      a
      (gcd b (remainder a b))))
@end lisp

@noindent
このアルゴリズムを実行するマシンは、@math{a}と@math{b}という2つの数値を追跡
しなければならないので、これらの数値がそれらの名前を持つ2つのレジスタに格納
されていると仮定しましょう。必要な基本操作は、レジスタ@code{b}の内容がゼロか
どうかをテストすることと、レジスタ@code{a}の内容をレジスタ@code{b}の内容で
割った余りを計算することです。余り操作は複雑なプロセスですが、今のところ、
余りを計算する原始デバイスがあると仮定しましょう。@abbr{GCD}アルゴリズムの
各サイクルで、レジスタ@code{a}の内容はレジスタ@code{b}の内容で置き換えられ、
@code{b}の内容は古い@code{a}の内容を古い@code{b}の内容で割った余りで置き換え
られなければなりません。これらの置き換えが同時に行われると便利ですが、レジスタ
マシンのモデルでは、各ステップで1つのレジスタにのみ新しい値を割り当てることが
できると想定します。置き換えを達成するために、マシンは3番目の「一時」レジスタを
使います。これを@code{t}と呼びます。（最初に余りが@code{t}に配置され、次に
@code{b}の内容が@code{a}に配置され、最後に@code{t}に格納された余りが@code{b}に
配置されます。）

@noindent
@ref{Figure 5.1}に示すデータパス図を使って、このマシンに必要なレジスタと操作を
示すことができます。この図では、レジスタ（@code{a}、@code{b}、@code{t}）は
長方形で表されます。レジスタに値を割り当てる各方法は、データのソースからレジスタへ
指す頭の後ろに@code{X}がある矢印で示されます。@code{X}は、押されるとソースの値が
指定されたレジスタに「流れる」ことを許可するボタンと考えることができます。
各ボタンの隣のラベルは、ボタンを参照するために使う名前です。名前は任意であり、
ニーモニック値を持つように選択できます（たとえば、@code{a<-b}は、レジスタ@code{b}の
内容をレジスタ@code{a}に割り当てるボタンを押すことを示します）。レジスタの
データのソースは、別のレジスタ（@code{a<-b}割り当てのように）、操作結果
（@code{t<-r}割り当てのように）、または定数（変更できない組み込み値で、データパス
図では定数を含む三角形で表されます）です。

@float
@anchor{Figure 5.1}
@ifinfo
@quotation
@strong{Figure 5.1:} @abbr{GCD}マシンのデータパス。

@example
                              ___
+-----+          +-----+     /   \
|  a  |<--(X)----|  b  +--->|  =  |
+--+--+   a<-b   +-+---+     \___/
   |               |  ^        ^
   +------+   +----+  |        |
          |   |      (X) b<-t  |
       .--+---+--.    |       / \
        \  rem  /     |      / O \
         \_____/      |     +-----+
            |         |
           (X) t<-r   |
            |         |
            V         |
         +-----+      |
         |  t  +------+
         +-----+
@end example
@end quotation
@end ifinfo
@iftex
@image{fig/chap5/Fig5.1a,105mm,,,.std.svg}
@caption{@strong{Figure 5.1:} @abbr{GCD}マシンのデータパス。}
@end iftex
@end float

定数とレジスタの内容から値を計算する操作は、データパス図では、操作の名前を
含む台形で表されます。たとえば、@ref{Figure 5.1}の@code{rem}とマークされた
ボックスは、接続されているレジスタ@code{a}と@code{b}の内容の余りを計算する
操作を表します。矢印（ボタンなし）は、入力レジスタと定数からボックスへ指し、
矢印は操作の出力値をレジスタに接続します。テストは、テストの名前を含む円で
表されます。たとえば、@abbr{GCD}マシンには、レジスタ@code{b}の内容がゼロか
どうかをテストする操作があります。テストには、入力レジスタと定数からの矢印も
ありますが、出力矢印はありません。その値は、データパスではなくコントローラに
よって使われます。全体として、データパス図は、マシンに必要なレジスタと操作、
およびそれらをどのように接続する必要があるかを示します。矢印をワイヤと考え、
@code{X}ボタンをスイッチと考えると、データパス図は電気部品から構築できるマシンの
配線図によく似ています。

@noindent
データパスが実際に@abbr{GCD}を計算するためには、ボタンを正しい順序で押さ
なければなりません。このシーケンスを、@ref{Figure 5.2}に示すコントローラ図の
観点から説明します。コントローラ図の要素は、データパスコンポーネントをどのように
操作すべきかを示します。コントローラ図の長方形のボックスは、押されるデータパス
ボタンを識別し、矢印はあるステップから次へのシーケンスを記述します。図のひし形は
決定を表します。データパステストで識別された値に応じて、2つのシーケンス矢印の
1つが続きます。コントローラは物理的な類似で解釈できます：図を、ビー玉が転がって
いる迷路と考えてください。ビー玉がボックスに転がると、ボックスで指定されたデータパス
ボタンを押します。ビー玉が決定ノード（@code{b} = 0のテストなど）に転がると、
指定されたテストの結果によって決定されたパスでノードを離れます。全体として、
データパスとコントローラは、@abbr{GCD}を計算するためのマシンを完全に記述します。
レジスタ@code{a}と@code{b}に数値を配置した後、@code{start}とマークされた場所で
コントローラ（転がるビー玉）を開始します。コントローラが@code{done}に到達すると、
レジスタ@code{a}に@abbr{GCD}の値が見つかります。

@float
@anchor{Figure 5.2}
@ifinfo
@quotation
@strong{Figure 5.2:} @abbr{GCD}マシンのコントローラ。

@example
     start
       |
       V
      / \ yes
+--->< = >-----> done
|     \ /
|      | no
|      V
|  +------+
|  | t<-r |
|  +---+--+
|      |
|      V
