変化の本質は、@newterm{手続き的認識論}と最もよく呼ばれるものの出現です---古典的な数学的主題によって取られるより宣言的な観点とは対照的に、命令的な観点からの知識の構造の研究。数学は、「何であるか」の概念を正確に扱うための枠組みを提供します。計算は、「どのように」の概念を正確に扱うための枠組みを提供します。

私たちの素材を教える際には、プログラミング言語Lispの方言を使用します。私たちは言語を正式に教えることはありません。なぜなら、その必要がないからです。私たちはそれを使用するだけで、学生は数日でそれを習得します。これは、Lispのような言語の大きな利点の1つです：複合式を形成する方法が非常に少なく、構文構造はほとんどありません。すべての形式的特性は、チェスのルールのように、1時間でカバーできます。短時間の後、私たちは言語の構文の詳細を忘れ（それらがないため）、実際の問題に取り掛かります---何を計算したいのか、問題を管理可能な部分にどのように分解するか、そして部分にどのように取り組むかを把握します。Lispのもう1つの利点は、私たちが知っている他のどの言語よりも、プログラムのモジュラー分解のための大規模な戦略をより多くサポート（しかし強制はしない）することです。私たちは、手続きとデータの抽象化を作成でき、高階関数を使用して使用法の共通パターンをキャプチャでき、代入とデータ変更を使用してローカル状態をモデル化でき、ストリームと遅延評価でプログラムの部分をリンクでき、埋め込み言語を簡単に実装できます。これらすべては、インクリメンタルなプログラム設計、構築、テスト、デバッグのための優れたサポートを備えたインタラクティブ環境に埋め込まれています。私たちは、John McCarthyから始まるすべての世代のLispウィザードに、前例のない力と優雅さの優れたツールを作り上げてくれたことに感謝します。

私たちが使用するLispの方言であるSchemeは、LispとAlgolの力と優雅さを統合する試みです。Lispからは、シンプルな構文、データオブジェクトとしてのプログラムの統一された表現、およびガベージコレクションされたヒープ割り当てデータから導かれるメタ言語的力を取ります。Algolからは、プログラミング言語設計の先駆者であるAlgol委員会のメンバーからの贈り物である字句スコープとブロック構造を取ります。私たちは、Churchのλ計算とプログラミング言語の構造との関係についての洞察について、John ReynoldsとPeter Landinを引用したいと思います。また、コンピュータが登場する数十年前にこの領域を開拓した数学者への私たちの負債を認識します。これらの先駆者には、Alonzo Church、Barkley Rosser、Stephen Kleene、Haskell Curryが含まれます。

@node       Acknowledgments, Chapter 1, Preface 1e, Top
@unnumbered 謝辞

この本とこのカリキュラムの開発を支援してくれた多くの人々に感謝したいと思います。

私たちの科目は、1960年代後半に@abbr{MIT}でJack WozencraftとArthur Evans, Jr.によって教えられたプログラミング言語学とλ計算に関する素晴らしい科目「6.231」の明確な知的子孫です。

私たちは、電気工学とコンピュータサイエンスにおける@abbr{MIT}の入門カリキュラムを再編成してエンジニアリング設計の原則を強調したRobert Fanoに大きな借りがあります。彼は私たちをこの事業に導き、この本が進化した最初の科目ノートを書きました。

私たちが教えようとしているプログラミングのスタイルと美学の多くは、Scheme言語の初期開発でGerald Jay Sussmanと協力したGuy Lewis Steele Jr.と共同で開発されました。さらに、David Turner、Peter Henderson、Dan Friedman、David Wise、Will Clingerは、この本に登場する関数型プログラミングコミュニティの多くの技術を私たちに教えてくれました。

Joel Mosesは、大規模なシステムの構造化について教えてくれました。彼のMacsyma記号計算システムでの経験は、制御の複雑さを避け、モデル化されている世界の実際の構造を反映するようにデータを整理することに集中すべきであるという洞察を提供しました。

Marvin MinskyとSeymour Papertは、プログラミングとそれが私たちの知的生活で占める位置についての私たちの態度の多くを形成しました。私たちは彼らに、計算が正確に扱うには複雑すぎるアイデアを探求するための表現手段を提供するという理解を負っています。彼らは、プログラムを書いて変更する学生の能力が、探求が自然な活動になる強力な媒体を提供することを強調しています。

私たちはまた、プログラミングが非常に楽しいものであり、プログラミングの喜びをサポートするように注意しなければならないというAlan Perlisに強く同意します。この喜びの一部は、偉大な巨匠が働くのを観察することから生じます。私たちは、Bill GosperとRichard Greenblattの足元で見習いプログラマーであったことは幸運でした。

私たちのカリキュラムの開発に貢献したすべての人々を特定することは困難です。過去15年間にわたって私たちと一緒に働き、私たちの科目に多くの追加時間を費やしたすべての講師、リサイテーションインストラクター、チューターに感謝します。特にBill Siebert、Albert Meyer、Joe Stoy、Randy Davis、Louis Braida、Eric Grimson、Rod Brooks、Lynn Stein、Peter Szolovitsに感謝します。私たちは、現在Wellesleyに在籍するFranklyn Turbakの優れた教育貢献を特に認めたいと思います。彼の学部教育での仕事は、私たちが皆が目指すことができる基準を設定しました。私たちは、並行性の謎に取り組むのを助けてくれたJerry SaltzerとJim Millerに感謝し、@ref{Chapter 4,,Chapter 4}の非決定性評価の説明への貢献についてPeter SzolovitsとDavid McAllesterに感謝します。

多くの人々が、他の大学でこの素材を発表するために多大な努力を払っています。私たちが密接に協力してきた人々の一部は、TechnionのJacob Katzenelson、カリフォルニア大学アーバイン校のHardy Mayer、オックスフォード大学のJoe Stoy、パデュー大学のElisha Sacks、ノルウェー科学技術大学のJan Komorowskiです。私たちは、イェール大学のKenneth Yip、カリフォルニア大学バークレー校のBrian Harvey、コーネル大学のDan Huttenloche
