@comment * Version 2.andresraba6.6 (September 16, 2015) by Andres Raba.
@comment   Fixed broken links. Tinted chapter and section numbers.
@comment   License updated to CC BY-SA 4.0.

@documentencoding UTF-8

@dircategory The Algorithmic Language Scheme
@direntry
* SICP: (sicp). 計算機プログラムの構造と解釈
@end direntry

@macro newterm{term}
@cindex \term\
@dfn{\term\}
@end macro

@setshortcontentsaftertitlepage

@titlepage

@titlefont{計算機プログラムの@*構造と解釈}

@subtitle 第2版@* Unofficial Texinfo Format @value{utfversion}

@author Harold Abelson and Gerald Jay Sussman with Julie Sussman, foreword by Alan J. Perlis

@page
@vskip 0pt plus 1filll
@noindent
@copyright{}1996 by The Massachusetts Institute of Technology

@noindent
@image{fig/icons/cc, 6mm,,,.std.svg}
@image{fig/icons/by, 6mm,,,.std.svg}
@image{fig/icons/sa, 6mm,,,.std.svg}

@noindent
この作品は Creative Commons Attribution-ShareAlike 4.0
International License (@url{http://creativecommons.org/licenses/by-sa/4.0/, @abbr{CC BY-SA 4.0}}) の下でライセンスされています。
@url{http://mitpress.mit.edu/sicp/, mitpress.mit.edu} の作品に基づいています。

@noindent
The @abbr{MIT} Press@*
Cambridge, Massachusetts@*
London, England

@noindent
McGraw-Hill Book Company@*
New York, St. Louis, San Francisco,@*
Montreal, Toronto

@noindent
本書は、マサチューセッツ工科大学の電気工学・計算機科学科の教員によって執筆された一連のテキストの1つです。本書は、The @abbr{MIT} Press と McGraw-Hill Book Company との共同制作・配給契約の下で、The @abbr{MIT} Press によって編集・制作されました。

@noindent
Unofficial Texinfo Format @url{http://sicpebook.wordpress.com, @value{utfversion}} (@value{utfversiondate}),
@url{http://www.neilvandyke.org/sicp-texi/, 2.neilvandyke4} (January 10, 2007) に基づく。

@end titlepage

@shortcontents

@contents

@headings off

@finalout

@node Top, UTF, (dir), (dir)

@ifinfo

@heading 計算機プログラムの構造と解釈

@noindent
第2版@*
Harold Abelson and Gerald Jay Sussman, with Julie Sussman 著@*
Alan J. Perlis による序文@*
@copyright{} 1996 Massachusetts Institute of Technology

@noindent
Unofficial Texinfo Format version @value{utfversion} (@value{utfversiondate})

@end ifinfo

@menu
* UTF::              Unofficial Texinfo Format
* Dedication::       献辞
* Foreword::         序文
* Preface::          第2版への序文
* Preface 1e::       第1版への序文
* Acknowledgments::  謝辞
* Chapter 1::        手続きによる抽象の構築
* Chapter 2::        データによる抽象の構築
* Chapter 3::        モジュール性、オブジェクト、状態
* Chapter 4::        メタ言語的抽象
* Chapter 5::        レジスタ計算機による計算
