ハードウェア技術のブレークスルーは、より大規模なプログラミング事業、新しい組織原理、および抽象モデルの充実につながります。すべての読者は、定期的に「何のために、何のために？」と自問すべきですが、ほろ苦い哲学の便秘のためにプログラミングの楽しみを諦めないように、あまり頻繁に尋ねないでください。

私たちが書くプログラムの中には、ソート、数列の最大値の検索、素数性の判定、平方根の検索など、正確な数学的関数を実行するもの（しかし決して十分ではない）があります。私たちはそのようなプログラムをアルゴリズムと呼び、特に実行時間とデータ格納要件という2つの重要なパラメータに関して、それらの最適な動作について多くのことが知られています。プログラマーは、優れたアルゴリズムとイディオムを習得すべきです。一部のプログラムは正確な仕様に抵抗しますが、パフォーマンスを見積もり、常に改善しようと試みることはプログラマーの責任です。

Lispは生存者であり、約四半世紀にわたって使用されています。アクティブなプログラミング言語の中で、Fortranだけがより長い寿命を持っています。両方の言語は、Fortranは科学および工学計算、Lispは人工知能という、重要なアプリケーション分野のプログラミングニーズをサポートしてきました。これらの2つの分野は引き続き重要であり、それらのプログラマーはこれらの2つの言語に非常に専念しているため、LispとFortranは少なくともさらに四半世紀の間アクティブに使用され続ける可能性があります。

Lispは変化します。このテキストで使用されているScheme方言は、元のLispから進化し、変数バインディングの静的スコープや関数が関数を値として生成することを許可するなど、いくつかの重要な点で後者とは異なります。その意味論的構造において、Schemeは初期のLispと同じくらいAlgol 60に近い親類です。Algol 60は、二度とアクティブな言語にはなりませんが、SchemeとPascalの遺伝子の中で生き続けています。これらの2つの言語を中心に集まった2つのまったく異なる文化の通貨となっている2つの言語を見つけることは困難です。Pascalはピラミッドを建設するためのものです---軍隊が重いブロックを所定の位置に押し込むことによって構築された、印象的で息をのむような静的な構造。Lispは生物を構築するためのものです---分隊が変動する無数のより単純な生物を所定の位置に適合させることによって構築された、印象的で息をのむようなダイナミックな構造。使用されている組織原理は両方の場合で同じですが、1つの非常に重要な違いを除いて：個々のLispプログラマーに委ねられた裁量的にエクスポート可能な機能は、Pascalエンタープライズ内で見つかるものよりも1桁以上大きいです。Lispプログラムは、それらを生成したアプリケーションを超えた有用性を持つ関数でライブラリを膨らませます。Lispのネイティブなデータ構造であるリストは、このような有用性の成長の大部分を担っています。リストのシンプルな構造と自然な適用性は、驚くほど非特異的な関数に反映されています。Pascalでは、宣言可能なデータ構造の過多が、カジュアルな協力を阻害し、ペナルティを課す関数内の特殊化を誘発します。100の関数が1つのデータ構造で動作する方が、10の関数が10のデータ構造で動作するよりも優れています。その結果、ピラミッドは千年間変わらずに立っていなければなりません。生物は進化するか滅びるかのどちらかです。

この違いを説明するために、この本内の素材と演習の扱いを、Pascalを使用する最初のコーステキストの扱いと比較してください。これが@abbr{MIT}でのみ消化可能なテキストであり、そこで見られる品種に特有であるという幻想の下で労働しないでください。それは、学生が誰であろうと、どこで使用されようと、Lispのプログラミングに関する真剣な本が正確になければならないものです。

これはプログラミングに関するテキストであり、ほとんどのLisp書籍とは異なり、人工知能での作業の準備として使用されることに注意してください。結局のところ、ソフトウェアエンジニアリングと人工知能の重要なプログラミング上の懸念は、調査中のシステムが大きくなるにつれて合体する傾向があります。これが、人工知能以外でLispへの関心が高まっている理由を説明しています。

その目標から期待されるように、人工知能研究は多くの重要なプログラミング問題を生み出します。他のプログラミング文化では、この問題の急増は新しい言語を生み出します。実際、非常に大規模なプログラミングタスクでは、有用な組織原理は、言語の発明を介してタスクモジュール内のトラフィックを制御および分離することです。これらの言語は、私たち人間が最も頻繁に対話するシステムの境界に近づくにつれて、あまり原始的でなくなる傾向があります。その結果、そのようなシステムには、複雑な言語処理関数が何度も複製されます。Lispは非常にシンプルな構文と意味論を持っているため、構文解析は基本的なタスクとして扱うことができます。したがって、構文解析技術はLispプログラムではほとんど役割を果たさず、言語プロセッサの構築が大規模なLispシステムの成長と変化の速度に対する障害になることはめったにありません。最後に、すべてのLispプログラマーが負担と自由を負っているのは、この構文と意味論の非常にシンプルさです。数行を超えるサイズのLispプログラムは、裁量的関数で飽和することなく書くことはできません。発明して適合させる。適合して再発明する！括弧のネスト内に思考を書くLispプログラマーに乾杯します。

@noindent
Alan J. Perlis@*
ニューヘブン、コネチカット

@node    Preface, Preface 1e, Foreword, Top
@unnumbered 第2版への序文

@quotation
ソフトウェアは他のものとは異なり、それが捨てられることを意図している可能性はありますか：全体のポイントは常にそれをシャボン玉として見ることですか？

---Alan J. Perlis
@end quotation


@noindent
この本の素材は、1980年以来@abbr{MIT}の入門レベルのコンピュータサイエンス科目の基礎となっています。第1版が出版されたとき、私たちはこの素材を4年間教えており、この第2版が登場するまでさらに12年が経過しました。私たちの
