@code{add-assertion!}?  Hint: Recall the definition of the infinite stream of
ones in @ref{3.5.2}: @code{(define ones (cons-stream 1 ones))}.

@lisp
(define (add-assertion! assertion)
  (store-assertion-in-index assertion)
  (set! THE-ASSERTIONS
        (cons-stream assertion 
                     THE-ASSERTIONS))
  'ok)
@end lisp
@end quotation

@node 4.4.4.6, 4.4.4.7, 4.4.4.5, 4.4.4
@subsubsection Stream Operations

The query system uses a few stream operations that were not presented in
@ref{Chapter 3}.

@code{Stream-append-delayed} and @code{interleave-delayed} are just like
@code{stream-append} and @code{interleave} (@ref{3.5.3}), except that
they take a delayed argument (like the @code{integral} procedure in 
@ref{3.5.4}).  This postpones looping in some cases (see @ref{Exercise 4.71}).

@lisp
(define (stream-append-delayed s1 delayed-s2)
  (if (stream-null? s1)
      (force delayed-s2)
      (cons-stream
       (stream-car s1)
       (stream-append-delayed (stream-cdr s1)
                              delayed-s2))))

(define (interleave-delayed s1 delayed-s2)
  (if (stream-null? s1)
      (force delayed-s2)
      (cons-stream
       (stream-car s1)
       (interleave-delayed 
        (force delayed-s2)
        (delay (stream-cdr s1))))))
@end lisp

@noindent
@code{Stream-flatmap}, which is used throughout the query evaluator to map a
procedure over a stream of frames and combine the resulting streams of frames,
is the stream analog of the @code{flatmap} procedure introduced for ordinary
lists in @ref{2.2.3}.  Unlike ordinary @code{flatmap}, however, we
accumulate the streams with an interleaving process, rather than simply
appending them (see @ref{Exercise 4.72} and @ref{Exercise 4.73}).

@lisp
(define (stream-flatmap proc s)
  (flatten-stream (stream-map proc s)))

(define (flatten-stream stream)
  (if (stream-null? stream)
      the-empty-stream
      (interleave-delayed
       (stream-car stream)
       (delay (flatten-stream
               (stream-cdr stream))))))
@end lisp

@noindent
The evaluator also uses the following simple procedure to generate a stream
consisting of a single element:

@lisp
(define (singleton-stream x)
  (cons-stream x the-empty-stream))
@end lisp

@node 4.4.4.7, 4.4.4.8, 4.4.4.6, 4.4.4
@subsubsection Query Syntax Procedures

@code{Type} and @code{contents}, used by @code{qeval} (@ref{4.4.4.2}),
specify that a special form is identified by the symbol in its @code{car}.
They are the same as the @code{type-tag} and @code{contents} procedures in
@ref{2.4.2}, except for the error message.

@lisp
(define (type exp)
  (if (pair? exp)
      (car exp)
      (error "Unknown expression TYPE"
             exp)))

(define (contents exp)
  (if (pair? exp)
      (cdr exp)
      (error "Unknown expression CONTENTS"
             exp)))
@end lisp

@noindent
The following procedures, used by @code{query-driver-loop} (in 
@ref{4.4.4.1}), specify that rules and assertions are added to the data base by
expressions of the form @code{(assert! ⟨@var{rule-or-assertion}⟩)}:

