@end lisp

@noindent
where @code{accumulation-function} can be things like @code{sum},
@code{average}, or @code{maximum}.  Ben reasons that it should be a cinch to
implement this.  He will simply feed the query pattern to @code{qeval}.  This
will produce a stream of frames.  He will then pass this stream through a
mapping function that extracts the value of the designated variable from each
frame in the stream and feed the resulting stream of values to the accumulation
function.  Just as Ben completes the implementation and is about to try it out,
Cy walks by, still puzzling over the @code{wheel} query result in 
@ref{Exercise 4.65}.  When Cy shows Ben the system's response, Ben groans,
``Oh, no, my simple accumulation scheme won't work!''

What has Ben just realized?  Outline a method he can use to salvage the
situation.
@end quotation

@quotation
@strong{@anchor{Exercise 4.67}Exercise 4.67:} Devise a way to install a loop
detector in the query system so as to avoid the kinds of simple loops
illustrated in the text and in @ref{Exercise 4.64}.  The general idea is that
the system should maintain some sort of history of its current chain of
deductions and should not begin processing a query that it is already working
on.  Describe what kind of information (patterns and frames) is included in
this history, and how the check should be made.  (After you study the details
of the query-system implementation in @ref{4.4.4}, you may want to
modify the system to include your loop detector.)
@end quotation

@quotation
@strong{@anchor{Exercise 4.68}Exercise 4.68:} Define rules to implement the
@code{reverse} operation of @ref{Exercise 2.18}, which returns a list
containing the same elements as a given list in reverse order.  (Hint: Use
@code{append-to-form}.)  Can your rules answer both @code{(reverse (1 2 3) ?x)}
and @code{(reverse ?x (1 2 3))}?
@end quotation

@quotation
@strong{@anchor{Exercise 4.69}Exercise 4.69:} Beginning with the data base and
the rules you formulated in @ref{Exercise 4.63}, devise a rule for adding
``greats'' to a grandson relationship. This should enable the system to deduce
that Irad is the great-grandson of Adam, or that Jabal and Jubal are the
great-great-great-great-great-grandsons of Adam.  (Hint: Represent the fact
about Irad, for example, as @code{((great grandson) Adam Irad)}.  Write rules
that determine if a list ends in the word @code{grandson}.  Use this to express
a rule that allows one to derive the relationship @code{((great .  ?rel) ?x
?y)}, where @code{?rel} is a list ending in @code{grandson}.)  Check your rules
on queries such as @code{((great grandson) ?g ?ggs)} and @code{(?relationship
Adam Irad)}.
@end quotation

@node	4.4.4, 4.4.4.1, 4.4.3, 4.4
@subsection Implementing the Query System

Section @ref{4.4.2} described how the query system works. Now we fill in the
details by presenting a complete implementation of the system.

@menu
* 4.4.4.1::          The Driver Loop and Instantiation
* 4.4.4.2::          The Evaluator
* 4.4.4.3::          Finding Assertions by Pattern Matching
* 4.4.4.4::          Rules and Unification
* 4.4.4.5::          Maintaining the Data Base
* 4.4.4.6::          Stream Operations
* 4.4.4.7::          Query Syntax Procedures
* 4.4.4.8::          Frames and Bindings
@end menu

@node 4.4.4.1, 4.4.4.2, 4.4.4, 4.4.4
@subsubsection The Driver Loop and Instantiation

The driver loop for the query system repeatedly reads input expressions.  If
the expression is a rule or assertion to be added to the data base, then the
information is added.  Otherwise the expression is assumed to be a query.  The
driver passes this query to the evaluator @code{qeval} together with an initial
frame stream consisting of a single empty frame.  The result of the evaluation
is a stream of frames generated by satisfying the query with variable values
found in the data base.  These frames are used to form a new stream consisting
of copies of the original query in which the variables are instantiated with
values supplied by the stream of frames, and this final stream is printed at
the terminal:

@lisp
(define input-prompt  ";;; Query input:")
(define output-prompt ";;; Query results:")

(define (query-driver-loop)
  (prompt-for-input input-prompt)
  (let ((q (query-syntax-process (read))))
    (cond ((assertion-to-be-added? q)
           (add-rule-or-assertion! 
            (add-assertion-body q))
           (newline)
           (display 
            "Assertion added to data base.")
           (query-driver-loop))
          (else
           (newline)
           (display output-prompt)
