
@end itemize

@quotation
@strong{@anchor{Exercise 2.97}Exercise 2.97:}
@enumerate a

@item
Implement this algorithm as a procedure @code{reduce-terms} that takes two term
lists @code{n} and @code{d} as arguments and returns a list @code{nn},
@code{dd}, which are @code{n} and @code{d} reduced to lowest terms via the
algorithm given above.  Also write a procedure @code{reduce-poly}, analogous to
@code{add-poly}, that checks to see if the two polys have the same variable.
If so, @code{reduce-poly} strips off the variable and passes the problem to
@code{reduce-terms}, then reattaches the variable to the two term lists
supplied by @code{reduce-terms}.

@item
Define a procedure analogous to @code{reduce-terms} that does what the original
@code{make-rat} did for integers:

@lisp
(define (reduce-integers n d)
  (let ((g (gcd n d)))
    (list (/ n g) (/ d g))))
@end lisp

and define @code{reduce} as a generic operation that calls @code{apply-generic}
to dispatch to either @code{reduce-poly} (for @code{polynomial} arguments) or
@code{reduce-integers} (for @code{scheme-number} arguments).  You can now
easily make the rational-arithmetic package reduce fractions to lowest terms by
having @code{make-rat} call @code{reduce} before combining the given numerator
and denominator to form a rational number.  The system now handles rational
expressions in either integers or polynomials.  To test your program, try the
example at the beginning of this extended exercise:

@lisp
(define p1 
  (make-polynomial 'x '((1 1) (0 1))))
(define p2 
  (make-polynomial 'x '((3 1) (0 -1))))
(define p3 
  (make-polynomial 'x '((1 1))))
(define p4 
  (make-polynomial 'x '((2 1) (0 -1))))
(define rf1 (make-rational p1 p2))
(define rf2 (make-rational p3 p4))
(add rf1 rf2)
@end lisp

See if you get the correct answer, correctly reduced to lowest terms.
@end enumerate
@end quotation

@noindent
The @abbr{GCD} computation is at the heart of any system that does
operations on rational functions.  The algorithm used above, although
mathematically straightforward, is extremely slow.  The slowness is due partly
to the large number of division operations and partly to the enormous size of
the intermediate coefficients generated by the pseudodivisions.  One of the
active areas in the development of algebraic-manipulation systems is the design
of better algorithms for computing polynomial @abbr{GCD}s.@footnote{One
extremely efficient and elegant method for computing polynomial @abbr{GCD}s
was discovered by Richard @ref{Zippel (1979)}.  The method is a probabilistic
algorithm, as is the fast test for primality that we discussed in @ref{Chapter
1}.  Zippel's book (@ref{Zippel 1993}) describes this method, together with other ways to
compute polynomial @abbr{GCD}s.}


@node    Chapter 3, 3.1, 2.5, Top
@chapter Modularity, Objects, and State

@quotation
Mεταβάλλον ὰναπαύεται@*
(Even while it changes, it stands still.)@*
---Heraclitus

Plus @,{c}a change, plus c'est la m@^{e}me chose.@*
---Alphonse Karr
@end quotation

@noindent
The preceding chapters introduced the basic elements from which programs are
made.  We saw how primitive procedures and primitive data are combined to
construct compound entities, and we learned that abstraction is vital in
helping us to cope with the complexity of large systems.  But these tools are
not sufficient for designing programs.  Effective program synthesis also
requires organizational principles that can guide us in formulating the overall
design of a program.  In particular, we need strategies to help us structure
large systems so that they will be @newterm{modular}, that is, so that they can
be divided ``naturally'' into coherent parts that can be separately developed
and maintained.

One powerful design strategy, which is particularly appropriate to the
construction of programs for modeling physical systems, is to base the
structure of our programs on the structure of the system being modeled.  For
each object in the system, we construct a corresponding computational object.
For each system action, we define a symbolic operation in our computational
model.  Our hope in using this strategy is that extending the model to
accommodate new objects or new actions will require no strategic changes to the
